### ISSUE TITLE
Support Google Fonts

### ISSUE THREAD

**Issue by coreybutler** [ngnjs/chassis#1]
Google fonts needs the font `@import` statement at the top (see [How to import google web font in css file](https://stackoverflow.com/questions/14676613/how-to-import-google-web-font-in-css-file)). 

Event when an `@import` is listed above the chassis init, `@import` is not generated at the top of the file.

**Source:**

![image](https://user-images.githubusercontent.com/770982/39391103-ff3c7dd6-4a63-11e8-8bd7-c2d3b652ac34.png)

**Output**

![image](https://user-images.githubusercontent.com/770982/39391104-03ab4cbc-4a64-11e8-8833-21189f66d15a.png)

**Comment by gbdrummer** [comment]
This has been fixed.
